chore(ci): support building ngx_wasm_module

diff --git a/.github/workflows/build_and_test.yml b/.github/workflows/build_and_test.yml
--- a/.github/workflows/build_and_test.yml
+++ b/.github/workflows/build_and_test.yml
@@ -33,6 +33,22 @@ jobs:
     - name: Checkout Kong source code
       uses: actions/checkout@v3
 
+    - name: Set ngx_wasm_module path/branch vars
+      run: |
+        grep ^NGX_WASM_MODULE_BRANCH= .requirements >> $GITHUB_ENV || {
+          echo "ERROR: NGX_WASM_MODULE_BRANCH is not defined in .requirements"
+          exit 1
+        }
+        echo "NGX_WASM_MODULE_REMOTE=$PWD/ngx_wasm_module" >> $GITHUB_ENV
+
+    - name: Checkout ngx_wasm_module
+      uses: actions/checkout@v3
+      with:
+        repository: Kong/ngx_wasm_module
+        path: ${{ env.NGX_WASM_MODULE_REMOTE }}
+        ref: ${{ env.NGX_WASM_MODULE_BRANCH }}
+        token: ${{ secrets.GHA_KONG_BOT_READ_TOKEN }}
+
     - name: Lookup build cache
       id: cache-deps
       uses: actions/cache@v3
